Algoritmo "qual_seu_nome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/09/2025
Var
 nome:caracter


Inicio
escreva("qual é o seu nome?")
leia( nome )
escreva("Olá ", nome ," é um prazer te conhecer!")


Fimalgoritmo